# Generated by Django 5.2.4 on 2025-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'kl_staff'), (3, 'law_firm_staff'), (4, 'investor')], null=True),
        ),
    ]
