# Generated by Django 5.2.4 on 2025-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Urgent')], default=20, null=True),
        ),
    ]
