# Generated by Django 5.2.4 on 2025-07-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0008_alter_fund_current_claims_sum_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='case_types',
            field=models.ManyToManyField(blank=True, to='litigation.casetype'),
        ),
    ]
