# Generated by Django 5.2.4 on 2025-07-28 15:59

import django.db.models.deletion
import djmoney.models.fields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0010_historicalinvestor_historicallawfirm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='litigation.casestatus'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='litigation.casetype'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='name',
            field=models.CharField(default='CaseStageDefault', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='name',
            field=models.CharField(default='CaseStatusDefault', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casetype',
            name='sender_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='sender_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='allowed_law_firms',
            field=models.ManyToManyField(blank=True, to='litigation.lawfirm'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='current_claims_sum',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='EUR', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='used_capital',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='EUR', max_digits=19),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='current_claims_sum',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='EUR', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='used_capital',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='EUR', max_digits=19),
        ),
        migrations.AlterField(
            model_name='investor',
            name='CaseTypes',
            field=models.ManyToManyField(blank=True, to='litigation.casetype'),
        ),
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case_status', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='litigation.casestatus')),
                ('case_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='litigation.casetype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('law_firm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='litigation.lawfirm')),
            ],
            options={
                'verbose_name': 'historical case',
                'verbose_name_plural': 'historical cases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCaseStage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case stage',
                'verbose_name_plural': 'historical case stages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCaseStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case status',
                'verbose_name_plural': 'historical case statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
