# Generated by Django 5.2.4 on 2025-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0011_case_case_status_case_case_type_casestage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcasestatus',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
